# Generated by Django 6.0.2 on 2026-02-12 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('face_shape', models.CharField(choices=[('Oval', 'Oval'), ('Round', 'Round'), ('Square', 'Square'), ('Long', 'Long'), ('Heart', 'Heart')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hairstyles/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='barbers/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('face_shape_detected', models.CharField(blank=True, max_length=20)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='appointments/')),
                ('preview_photo', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.barber')),
                ('hairstyle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hairstyle')),
            ],
        ),
    ]
