# Generated by Django 6.0.2 on 2026-02-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐⭐'), (3, '3 ⭐⭐⭐'), (4, '4 ⭐⭐⭐⭐'), (5, '5 ⭐⭐⭐⭐⭐')], default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='booking.appointment')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='booking.barber')),
            ],
        ),
    ]
